name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - x86_64-pc-windows-msvc
        - x86_64-unknown-linux-gnu
        - x86_64-apple-darwin
        include:
        - build: x86_64-pc-windows-msvc
          os: windows-latest
          target: x86_64-pc-windows-msvc
        - build: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - build: x86_64-apple-darwin
          os: macos-13
          target: x86_64-apple-darwin
        - build: aarch64-apple-darwin
          os: macos-latest
          target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --target=${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
